version: "3"

services:

  nginx:
    image: nginx:latest
    container_name: ${APP_NAME}_nginx
    ports:
      - 80:80
      - 8080:80
    volumes:
      - .:/usr/share/nginx/html:rw
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d

  php-fpm:
    build: .docker/php-fpm
    container_name: ${APP_NAME}_php
    volumes:
      - .:/usr/share/nginx/html:rw

  mysql:
    image: mysql:5.7
    container_name: ${APP_NAME}_mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    restart: always
